// Code generated by kate-gen. DO NOT EDIT.
//
// Source: 用户注册信息维表
//
// Table: hmct.dim_user_reg

package dim_user_reg

import (
	"github.com/stn81/kate/datetime"
	ksql "github.com/stn81/kate/orm/sql"
)

// Row is the scan target for a row of hmct.dim_user_reg.
type Row struct {
	Userid                         uint64                    `db:"userid"` // 用户ID
	RegChannel                     string                    `db:"reg_channel"` // 注册渠道
	RegAppVersion                  string                    `db:"reg_app_version"` // 注册版本
	RegIP                          string                    `db:"reg_ip"` // 注册IP
	RegPhoneBrand                  string                    `db:"reg_phone_brand"` // 注册时手机品牌（取 ct_user_device 该 userid argMin(create_time) 记录的 phone_brand）
	RegPhoneModel                  string                    `db:"reg_phone_model"` // 注册时手机型号（取 ct_user_device 该 userid argMin(create_time) 记录的 phone_model）
	RegTime                        datetime.DateTime         `db:"reg_time"` // 注册时间
	Nickname                       string                    `db:"nickname"` // 昵称
	CreateTime                     datetime.DateTime         `db:"create_time"` // 创建时间
	UpdateTime                     datetime.DateTime         `db:"update_time"` // 更新时间
}

// T is the typed descriptor for hmct.dim_user_reg — embeds ksql.TableRef and exposes one ksql.Col[T] per column.
var T = struct {
	ksql.TableRef
	Userid                         ksql.Col[uint64]
	RegChannel                     ksql.Col[string]
	RegAppVersion                  ksql.Col[string]
	RegIP                          ksql.Col[string]
	RegPhoneBrand                  ksql.Col[string]
	RegPhoneModel                  ksql.Col[string]
	RegTime                        ksql.Col[datetime.DateTime]
	Nickname                       ksql.Col[string]
	CreateTime                     ksql.Col[datetime.DateTime]
	UpdateTime                     ksql.Col[datetime.DateTime]
}{
	TableRef: ksql.NewTable("hmct", "dim_user_reg", ""),
	Userid:                        ksql.NewCol[uint64]("hmct", "dim_user_reg", "userid"),
	RegChannel:                    ksql.NewCol[string]("hmct", "dim_user_reg", "reg_channel"),
	RegAppVersion:                 ksql.NewCol[string]("hmct", "dim_user_reg", "reg_app_version"),
	RegIP:                         ksql.NewCol[string]("hmct", "dim_user_reg", "reg_ip"),
	RegPhoneBrand:                 ksql.NewCol[string]("hmct", "dim_user_reg", "reg_phone_brand"),
	RegPhoneModel:                 ksql.NewCol[string]("hmct", "dim_user_reg", "reg_phone_model"),
	RegTime:                       ksql.NewCol[datetime.DateTime]("hmct", "dim_user_reg", "reg_time"),
	Nickname:                      ksql.NewCol[string]("hmct", "dim_user_reg", "nickname"),
	CreateTime:                    ksql.NewCol[datetime.DateTime]("hmct", "dim_user_reg", "create_time"),
	UpdateTime:                    ksql.NewCol[datetime.DateTime]("hmct", "dim_user_reg", "update_time"),
}

// TableName returns the qualified table name for ORM-style lookups.
func (*Row) TableName() string { return "hmct.dim_user_reg" }

// ToMap returns the row as map[string]any keyed by SQL column name.
func (r *Row) ToMap() map[string]any {
	return map[string]any{
		"userid": r.Userid,
		"reg_channel": r.RegChannel,
		"reg_app_version": r.RegAppVersion,
		"reg_ip": r.RegIP,
		"reg_phone_brand": r.RegPhoneBrand,
		"reg_phone_model": r.RegPhoneModel,
		"reg_time": r.RegTime,
		"nickname": r.Nickname,
		"create_time": r.CreateTime,
		"update_time": r.UpdateTime,
	}
}
