package codegen

import (
	"fmt"
	"sort"
	"strings"
)

// Emit produces the Go source for one table package.
func Emit(t *Table, pkgName string) (string, error) {
	if len(t.Columns) == 0 {
		return "", fmt.Errorf("table %s has no columns", t.Name)
	}
	var b strings.Builder
	b.WriteString("// Code generated by kate-gen. DO NOT EDIT.\n")
	b.WriteString("//\n")
	if t.Comment != "" {
		b.WriteString("// Source: " + escGoComment(t.Comment) + "\n//\n")
	}
	b.WriteString("// Table: " + qualifiedTable(t) + "\n")
	b.WriteString("\n")
	b.WriteString("package " + pkgName + "\n\n")

	imports := collectImports(t)
	// kate sql import is always needed for Col/TableRef.
	imports["github.com/stn81/kate/orm/sql"] = true
	if needsImport(t, "time.Time") {
		imports["time"] = true
	}
	emitImports(&b, imports)

	emitRow(&b, t)
	emitDescriptor(&b, t)
	emitTableName(&b, t)
	emitToMap(&b, t)
	return b.String(), nil
}

func qualifiedTable(t *Table) string {
	if t.Schema != "" {
		return t.Schema + "." + t.Name
	}
	return t.Name
}

// collectImports gathers extra import paths required by column Go types.
func collectImports(t *Table) map[string]bool {
	out := map[string]bool{}
	for _, c := range t.Columns {
		if c.GoImport != "" {
			out[c.GoImport] = true
		}
	}
	return out
}

// needsImport reports whether any column Go type mentions s as a substring.
// Used to decide if the "time" package import is needed.
func needsImport(t *Table, s string) bool {
	for _, c := range t.Columns {
		if strings.Contains(c.GoType, s) {
			return true
		}
	}
	return false
}

func emitImports(b *strings.Builder, imports map[string]bool) {
	if len(imports) == 0 {
		return
	}
	keys := make([]string, 0, len(imports))
	for k := range imports {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	b.WriteString("import (\n")
	for _, k := range keys {
		// kate's sql package import gets an alias to avoid shadowing the
		// stdlib "database/sql" callers may also pull in.
		if k == "github.com/stn81/kate/orm/sql" {
			b.WriteString("\tksql \"" + k + "\"\n")
		} else {
			b.WriteString("\t\"" + k + "\"\n")
		}
	}
	b.WriteString(")\n\n")
}

// emitRow writes the Row struct.
func emitRow(b *strings.Builder, t *Table) {
	b.WriteString("// Row is the scan target for a row of " + qualifiedTable(t) + ".\n")
	b.WriteString("type Row struct {\n")
	for _, c := range t.Columns {
		field := goFieldName(c.Name)
		comment := ""
		if c.Comment != "" {
			comment = " // " + escGoComment(c.Comment)
		}
		fmt.Fprintf(b, "\t%-30s %-25s `db:\"%s\"`%s\n", field, c.GoType, c.Name, comment)
	}
	b.WriteString("}\n\n")
}

// emitDescriptor writes the typed table descriptor T.
func emitDescriptor(b *strings.Builder, t *Table) {
	b.WriteString("// T is the typed descriptor for " + qualifiedTable(t) +
		" — embeds ksql.TableRef and exposes one ksql.Col[T] per column.\n")
	b.WriteString("var T = struct {\n")
	b.WriteString("\tksql.TableRef\n")
	for _, c := range t.Columns {
		field := goFieldName(c.Name)
		fmt.Fprintf(b, "\t%-30s ksql.Col[%s]\n", field, c.GoType)
	}
	b.WriteString("}{\n")
	fmt.Fprintf(b, "\tTableRef: ksql.NewTable(%q, %q, \"\"),\n", t.Schema, t.Name)
	for _, c := range t.Columns {
		field := goFieldName(c.Name)
		fmt.Fprintf(b, "\t%-30s ksql.NewCol[%s](%q, %q, %q),\n", field+":", c.GoType, t.Schema, t.Name, c.Name)
	}
	b.WriteString("}\n\n")
}

// emitTableName writes a TableName() string method on *Row for callers that
// still rely on the legacy beego-style API.
func emitTableName(b *strings.Builder, t *Table) {
	b.WriteString("// TableName returns the qualified table name for ORM-style lookups.\n")
	b.WriteString("func (*Row) TableName() string { return ")
	if t.Schema != "" {
		fmt.Fprintf(b, "%q", t.Schema+"."+t.Name)
	} else {
		fmt.Fprintf(b, "%q", t.Name)
	}
	b.WriteString(" }\n\n")
}

// emitToMap writes Row.ToMap() returning a map[string]any keyed by the
// SQL column name. Replaces JSON round-trip patterns at scan-time.
func emitToMap(b *strings.Builder, t *Table) {
	b.WriteString("// ToMap returns the row as map[string]any keyed by SQL column name.\n")
	b.WriteString("func (r *Row) ToMap() map[string]any {\n")
	fmt.Fprintf(b, "\treturn map[string]any{\n")
	for _, c := range t.Columns {
		field := goFieldName(c.Name)
		fmt.Fprintf(b, "\t\t%q: r.%s,\n", c.Name, field)
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")
}

// goFieldName converts snake_case to CamelCase, preserving common
// abbreviations (ID, URL, IP, ECPM) in uppercase.
func goFieldName(s string) string {
	parts := strings.Split(s, "_")
	abbr := map[string]bool{
		"id": true, "url": true, "ip": true, "ui": true, "ua": true,
		"os": true, "api": true, "uid": true, "ecpm": true, "cpa": true,
	}
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		if abbr[p] {
			b.WriteString(strings.ToUpper(p))
		} else {
			b.WriteString(strings.ToUpper(p[:1]))
			b.WriteString(p[1:])
		}
	}
	return b.String()
}

// escGoComment makes a CK comment safe for a Go line comment: strips
// newlines and backticks.
func escGoComment(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "`", "'")
	return s
}
